limits-service:
    maximum: 999
    minimum: 3
spring:
    application:
        name: limits-service
    cloud:
        config:
            profile: qa
    config:
        import: optional:configserver:http://localhost:8888
    profiles:
        active: dev
